@hostnamea = aicorr3-fn-a.azurewebsites.net
@hostnameb = aicorr3-fn-b.azurewebsites.net
## if needed declare host and port e.g. localhost:8080
@hosta = {{hostnamea}}
@hostb = {{hostnameb}}
@contentType = application/json
@protocol = https
@submissionid = {{$guid}}


POST {{protocol}}://{{hosta}}/api/queue/{{submissionid}} HTTP/1.1
Request-Context: appId=cid-v1:188acaa8-2fff-43f9-bc0c-bde9d84793af

### USING FUNCTION A PUT A MSG ON A QUEUE TO BE PICKED UP BY FUNCTION B
@submissionid = {{$guid}}
POST {{protocol}}://{{hosta}}/api/queue-with-bagage/{{submissionid}} HTTP/1.1


### USING FUNCTION A CALL AN EXTERNAL HTTP ENDPOINT
GET {{protocol}}://{{hosta}}/api/callexternalhttpurl HTTP/1.1



### USING FUNCTION A CALL FUNCTION B OVER HTTP, GET A RESPONSE BACK
GET {{protocol}}://{{hosta}}/api/callhttpwithrespfromb


### USING FUNCTION A CALL LOGIC APP A
GET {{protocol}}://{{hosta}}/api/calllogicappa


### USING FUNCTION A CALL LOGIC APP A WiTH BAGGAGE
# GET http://{{hosta}}/api/calllogicappa/{{submissionid}}


### USING FUNCTION A CALL LOGIC APP A WiTH BAGGAGE AND CONTENT; LOGIC APP TO CALL INTO A URL

GET http://{{hosta}}/api/calllogicappa/{{submissionid}}
content-type: application/json

{
    "logicAppAction": "callIntoUrl",
    "url": "http://requestbin.net/r/10opbi51"
}

### USING FUNCTION A CALL LOGIC APP A WiTH BAGGAGE AND CONTENT; LOGIC APP TO CALL INTO A FUNCTION

GET http://{{hosta}}/api/calllogicappa/{{submissionid}}
content-type: application/json

{
    "logicAppAction": "callIntoUrl",
    "url": "http://{{hostb}}/api/http"
}

GET {{protocol}}://{{hosta}}/api/calllogicappa/{{submissionid}}

### test event grid function for functionappA
@rg = xstof
@subscriptionid =09a55fcd-23ab-4b16-98b7-c17f85e641d5
@resourceprefix = begim
@eventId = {{$guid}}

POST https://begim-egtopic.northeurope-1.eventgrid.azure.net/api/events
Content-Type: application/json
aeg-event-type: Notification
aeg-sas-key: /q94V0gMByVR6T2HSW21Fq7Xl7EHhBfbrpvOuFoMFS0=

[
  {
    "topic": "/subscriptions/{{subscriptionid}}/resourceGroups/{{rg}}/providers/Microsoft.EventGrid/topics/begim-egtopic",
    "subject": "test",
    "id": "{{eventId}}",
    "eventType": "test",
    "eventTime": "{{$localDatetime iso8601}}",
    "data":{
      "propertyA":"test"
    },
    "dataVersion": "1.0",
    "metadataVersion": "1"
  }
]

